config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/" => 'users#home'
  get "/products" => 'products#all_index'
  get "/products/:id" => 'products#product_show'
  get "/products/:id/reviews" => 'reviews#index'
  
  resources :users, only: [:show] do
    resources :products, only: [:index, :create, :new, :destroy] do
      resources :reviews, only: [:create, :new]
      resources :bids, only: [:create, :new]
    end
  end

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :bids
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :email, uniqueness: true, presence: true

  has_many :products
  has_many :bids
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  	def configure_permitted_parameters
  		devise_parameter_sanitizer.for(:sign_up) << :name
  	end

  

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
	
	before_action :authenticate_user!

	def create
	end
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

		before_action :authenticate_user!, except: [:all_index, :product_show]

	def all_index
		@products = Product.all
	end

	def product_show
		@product = Product.find_by(id: params[:id])
		@reviews = @product.reviews.all
		@user = current_user
		@review = @product.reviews.new

	end

	def index
		@user = User.find_by(id: params[:user_id])
		@products = @user.products.all
	end

	def create
		@user = User.find_by(id: params[:user_id])
		@product = @user.products.new(product_params)
		if @product.save
			redirect_to user_products_path(@user)
		else
			render 'new'
		end
	end

	def new
		@user = User.find_by(id: params[:user_id])
		@product = @user.products.new
	end

	def destroy
	end

	private
	def product_params
		params.require(:product).permit(:title, :deadline, :description)
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
		before_action :authenticate_user!, except: :index

	def index
		@user = current_user
		@product = Product.find_by(id: params[:id])
		@reviews = @product.reviews.all
	end

	def create
		@user = current_user
		@product = Product.find_by(id: params[:product_id])
		@review = @product.reviews.new(review_params)
		@review.user = @user
		@review.save
		render json: @product.to_json(:include => :reviews)
	end

	def new
		@user = current_user
		@product = Product.find_by(id: params[:id])
		@review = @product.reviews.new
	end

	private
	def review_params
		params.require(:review).permit(:title, :description)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!, only: :show

	def home
		@user = current_user
	end

	def show
		@user = User.find_by(params[:id])
		render 'users/show'
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuctionSite</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <% if current_user %>
      <ul class="nav navbar-nav">
        <li><%= link_to("All Products", products_path) %><span class="sr-only"></span></li>
        <li><a href="/users/<%=current_user.id%>/products">My Products</a></li>
        <li><a href="/users/<%=current_user.id%>/products/new">Add Products</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/users/sign_out" data-method="DELETE">Log out</a></li>
      </ul>
    <% else %>
    	<ul class="nav navbar-nav">
        <li><%= link_to("All Products", products_path) %><span class="sr-only"></span></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/users/sign_in">Log In</a></li>
        <li><a href="/users/sign_up">Sign Up</a></li>
      </ul>
    <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>

app/views/products/all_index.html.erb
<h1>All Products:</h1>
<ul>
	<% @products.each do |product| %>
		<li>
			<p>Product: <%= link_to("#{product.title}", "/products/#{product.id}") %></p>
			<p>Deadline: <%= product.deadline %></p>
		</li>
	<% end %>
</ul>
<p><%= link_to("Back to the Homepage", "/") %></p>

app/views/products/index.html.erb
<h1>Welcome to <%= @user.name %>'s Products' Page</h1>
<ul>
	<% @products.each do |product| %>
		<li>
			<h4><%= link_to("#{product.title}", "/products/#{product.id}") %> | <%= product.deadline %></h4>
		</li>
	<% end %>
</ul>

app/views/products/new.html.erb
<h1>List a new product!</h1>
<ul>
	<% if @product.errors.any?  %>
		<% @product.errors.full_messages.each do |error_message| %>
			<li><%= error_message %></li>
		<% end %>
	<% end %>
</ul>

<h3>Fill out the form below:</h3>

<%= form_for [@user, @product] do |f| %>
 <%= f.label :title %>
 <%= f.text_field :title %>
<br><br>
	<%= f.label :deadline %>
	<%= f.datetime_local_field :deadline %>
<br><br>
	<%= f.label :description %>
	<%= f.text_area :description %>
<br><br>
	<%= f.submit :class => "btn btn-primary" %><br>
	<%= link_to("Cancel", user_path(@user.id)) %>
	<%= link_to("Home", "/") %>
<% end %>

app/views/products/product_show.html.erb
<h1>Product Details:</h1>
<h3><%= @product.title %></h3>
<p><strong>Deadline:</strong><br>
	<%= @product.deadline %><p>
<p><strong>Description:</strong><br>
	<%= @product.description %>
</p><br><br>
<h4>Comments</h4>
<hr>
<%= render "/reviews/index" %>
<% if current_user %>
	<br>
	<%= render "/reviews/new" %>
<% end %>

app/views/reviews/_index.html.erb
<ul class="js-product-comments">
	<% @reviews.each do |review| %>
		<li><h5><%= review.title %></h5>
		<p><%= review.description %></p></li>
		<hr>
	<% end %>
</ul>

app/views/reviews/_new.html.erb
<%= form_for [@user, @product, @review] do |f| %>
 <%= f.label :title %><br>
 <%= f.text_field :title %>
<br><br>
	<%= f.label :description %><br>
	<%= f.text_area :description %>
<br><br>
	<%= f.submit :class => "btn btn-primary js-review-button", :data => {:user_id => @user.id, :product_id => @product.id, :current_user_id => current_user.id } %>
<br><br>
	<%= link_to("Cancel", user_path(@user.id)) %>
<% end %>

app/views/users/home.html.erb
<h1>Welcome to the Auction Site</h1>
<% if current_user.nil? %>
	
	<p>Description about this auction site!</p>

	<%= link_to("Sign Up", new_user_registration_path) %><br>
	<%= link_to("Log In", new_user_session_path) %>

<% else %>
	<%= "Hey #{@user.name}, welcome back!" %>
	<br><br>
	<%= link_to("Check out what's for sale, BUY now!", products_path) %><br>
	<%= link_to("Make some dough, SELL something", new_user_product_path(@user.id)) %>
	
<% end %>